version: "2"
  db:
    container_name: mysql_database
    image: mysql/mysql-server
    ports:
      - "33060:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=itsasecret
    volumes:
      - persistent:/var/lib/mysql
  flask:
    container_name: pythonService
    build: .
    image: python_service
    command: python2 App.py
    ports:
      - "9000:5000"
    volumes:
      - ./python_api:/code
    links:
      - db
    depends_on:
      - db
volumes:
    persistent:
